apiVersion: v1
kind: Service
metadata:
  name: campus-maps-service
spec:
  type: NodePort
  selector:
    app: campus-maps
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
